import type { Metadata } from "next";
import { Playpen_Sans, Rubik } from "next/font/google";
import "./globals.css";
import { HeroHeader } from "@/components/home-page/header";
import FooterSection from "@/components/home-page/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playpen = Playpen_Sans({
  variable: "--font-shadow",
  weight: "300",
  style: "normal"
})

const rubik = Rubik({
  variable: "--font-shadow",
  weight: "300",
  style: "normal"
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className}`}
      > 
        <div className="flex min-h-screen flex-col">
        <HeroHeader />
      <main className="flex-grow">{children}</main>
      <FooterSection />
    </div>
      </body>
    </html>
  );
}
